### ISSUE TITLE
Creating layer fails in versions > 2.8.2

### ISSUE THREAD

**Issue by RGunning** [agutoli/serverless-layers#168]
Creating layers with serverless-layer > 2.8.2 fails at `fs.rmSync` added by #153

```

[ LayersPlugin ]: => common
... ○ Downloading ./serverless-layers/common/package.json from bucket...
... ○ Comparing package.json dependencies...
... ○ Downloading customHash.json from bucket...
... ○ Uploading remote customHash.json...
... ○ OK...
... ○ identified custom hash change!
... ○  Changes identified ! Re-installing...
... ∅ [warning] ".npmrc" file does not exists!
... ∅ [warning] "package-lock.json" file does not exists!
... ○ yarn --production 

✖ Stack asset failed to deploy (3s)
Environment: darwin, node 20.10.0, framework 3.38.0 (local), plugin 7.2.2, SDK 4.5.1
Credentials: Local, environment variables
Docs:        docs.serverless.com
Support:     forum.serverless.com
Bugs:        github.com/serverless/serverless/issues

Error:
Error: Command failed: yarn --production 
    at checkExecSyncError (node:child_process:890:11)
    at execSync (node:child_process:962:15)
    at /node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:87:41
    at handleSubProcessSync (/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:31:36)
    at childProcess.execSync (/node_modules/cli-progress-footer/lib/private/cli-progress-footer/disable-props.js:86:11)
    at Dependencies._callee2$ (/node_modules/serverless-layers/src/package/Dependencies.js:78:12)
    at tryCatch (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
    at Generator.next (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at /node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Dependencies.<anonymous> (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12)
    at Dependencies.run (/node_modules/serverless-layers/src/package/Dependencies.js:83:4)
    at Dependencies._callee3$ (/node_modules/serverless-layers/src/package/Dependencies.js:133:61)
    at tryCatch (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
    at Generator.next (/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
```

removing the rmsync from https://github.com/agutoli/serverless-layers/commit/4fe97ad4ec86a650655278a36d8ac4d3fa4fe2df#diff-c6c92d94f94a5c56616b85c40199e51b8e1da32af1d68b97a7053701e67de621R24 and the build works again

**Comment by RGunning** [comment]
should be handled by https://github.com/agutoli/serverless-layers/pull/156
